apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      env: production

  template:
    metadata:
      name: nodejsapp
      labels:
       env: production

    spec:
      containers:
      - name: nodejsapp
        image: vaibhavhexaview/nodejs-app:v1.1
